probot/stale

- README.md
- index.js
- lib/defaults.js
- lib/stale.js
- package.json
Configuration in `.github/stale.yml` can override these defaults:
```yml
days: 60
exemptLabels:
- pinned
- security
staleLabel: wontfix
markComment: >
This issue has been automatically marked as stale because it has not had
recent activity. It will be closed if no further activity occurs. Thank you
for your contributions.
closeComment: false
```
cc @lee-dohm
> Get config from .github/stale.yml

- README.md
- index.js
This is a hotfix for #2 because it's already proven disorienting for the bot to run on a repo on install.
> Dry-run on repos without a config

- lib/stale.js
This checks for the existence of the stale label and creates it if it doesn't exist whenever doing the mark and sweep on issues.
Fixes #3
> Create the staleLabel if it does not exist

- README.md
- lib/defaults.js
- lib/stale.js
Replaces `days` config with 2 separate configs:
```yml
daysUntilStale: 60
daysUntilClose: 7
```
Fixes #12 @rafaelfranca
> Separate timeframes for stale and close activity

- README.md
Without a `.github/stale.yml` file, the integration will remain
inactive.
@bkeepers not sure about the wording, it might be a bit klunky.
> Document explicit permissions

- index.js
Fixes for a couple common sources of errors in the logs:
1. If a repo does not have a config, stop checking every hour
2. When activity happens on a PR, look for the `pull_request` payload.
> Stop visiting

- README.md
- lib/defaults.js
- lib/stale.js
- package.json
This adds an `unmarkComment` config that will be posted when the stale label is removed:
```yml
unmarkComment: Thanks for commenting. This issue is no longer marked as stale.
```
Fixes #20 
cc @rallytime
> Comment when removing stale label

- lib/stale.js
Some labels can have spaces on it and without quotes the query string will be invalid.
The previous code was generating invalid queries when the label contained spaces and no issues were being returned.
I tested in my ruby on rails integration (I deployed a different integration to be able to debug).
> Wrap labels on quotes

- index.js
This fixes #18 by adding two guards:
1. Don't unmark if the issue is closed
2. Don't unmark if the stale label was just added
cc @kytrinyx @kotp
> Don't unmark in a few situations

- package.json
Probot [currently specifies](https://github.com/probot/probot/blob/master/package.json):
```json
"engines": {
"node": "^7.7"
}
```
Since 0.8 was released, deploys are currently broken, so updating this until a new release of probot is pushed out.
> More explicit node versions

- index.js
- lib/stale.js
- package.json
This updates to the latest probot, using `context.github`, which was introduced in 0.5.0, and updating uses of the GitHub client to always look for `res.data` (cc https://github.com/mikedeboer/node-github/pull/505).
cc https://github.com/probot/probot/pull/153 for the next release of probot
> Use latest probot and github client

- index.js
Fixes issue where untrusted yaml file could contain JavaScript: https://github.com/nodeca/js-yaml#safeload-string---options-
> Use yaml.safeLoad instead of load

- README.md
- lib/stale.js
Repositories with a lot of open issues tend to trigger abuse mechanisms on GitHub. This limits it to 30 issues in an attempt to reduce errors. Repositories with more than 30 stale issues will have to wait for multiple runs (every hour) for all open issues to be marked.
Should fix #26
> Limit to 30 issues per run

- lib/stale.js
In case the app still triggers the abuse detection (https://github.com/probot/stale/issues/26), this ensures that it tries the abusive activity (commenting) first, and then follows up the non-abusive activity (label).
> Comment before labeling

- lib/stale.js
- package.json
- test/stale.js
Hi,
this catches any 404 error thrown by the GitHub-API when the client tries to remove a label which no longer exists on the specific issue / PR (described in #52 by @bkeepers ). I also added a test file and tried to make it similar to tests from other repos within the probot organization.
> On unmark, ignore if stale label has already been removed

- README.md
See #71
Stale gets confused when label names use square brackets. Until this is fixed, let's show that one can work around that problem by adding quotes around the label.
> Include an example of a label with square brackets

- README.md
- index.js
- lib/stale.js
- test/stale.test.js
Hello, and thanks for the useful bot! 
You recommended I make a PR, and I hope this makes the bot even better.
This PR does two things:
* Closes #66: Feature Request: different stale settings for PRs and Issues
* Most configs can be specified for just 'pulls' or 'issues' as overrides for the 'global' config values.
* The config values for `owner`, `repo`, `only`, and `logger` all remain 'global' only.
* Add config 'limitPerRun'
* Limit per run is still capped at 30, but the config can now set it lower.
* This will let me start chipping away at old issues at 1 per hour instead of getting a huge flood.
This should all be backward compatible, and examples for the new configs are added to the `README`.
~Unfortunately I was not able to easily find a way to test this out.~
~I have looked it …
> Allow different settings for pulls and issues. Add config 'limitPerRun'.

- .travis.yml
- package.json
Noticed while helping @tcbyrd out with #84 that `mocha` is the dependency in the tests, but `jest` was being used to run the tests.
We can migrate to jest in a separate PR, but this should get the tests running on Travis.
> Get Travis running & tests passing

- README.md
- lib/defaults.js
- lib/stale.js
This PR adds the ability to ignore issues assigned to a project or milestone without needing to look for a specific label.
> Add ability to ignore issues in a Project or Milestone

- lib/stale.js
If someone sets a very large value in `daysUntilStale` or `daysUntilClose`, GitHub will return an error:
`{"message":"Validation Failed","errors":[{"message":"The year 1744 in \"1744-04-29T04:07:36\" is outside the accepted range 1970 to 2970.","resource":"Search","field":"q","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/search/"}`
This is a temporary work around to just set 1970 as the minimum date for any query.
#92 should include a long-term fix for this.
> Fix dates before 1970

- lib/schema.js
- test/schema.test.js
#92 introduced a bug where as soon as you added one value to the `issues` or `pulls` options introduced in #69, then all other keys would get the default values, obscuring any top-level options.
To reproduce, use this config:
```yaml
daysUntilStale: 60
staleLabel: stale
issues:
daysUntilStale: 90
```
Even though `issues` doesn't define `staleLabel`, it would get the default value (`wontfix`), obscuring the value set at the top level.
Fixes #95 
cc @mezz
> Fix bug where `pulls` and `issues` config get all defaults

- lib/stale.js
At certain places like line 22 in stale.js we haven't used Object destructuring but at other places we do that. This definitely makes the code inconsistent. This PR fixes that
> fixes #100 by using object destructuring

- .github/stale.yml
- index.js
- lib/schema.js
- package.json
- test/schema.test.js
The `probot-config` package has a nice feature where it allows you to inherit configuration from another repository:
```
_extends: .github
daysUntilStale: 90
```
I'm going to start experimenting with this pattern and see about making it a feature of the built-in `context.config(…)` method.
> Use probot-config to allow inheriting config from another repo

- lib/stale.js
- test/stale.test.js
- Tests 
- Added regression tests for daysUntilClose keyword when using pulls or issues keyword
- Added regression tests for only keyword when using pulls or issues keyword
- Fix so daysUntilClose can be used under the pulls or issues keyword
- Fix so only can be used under the pulls or issues keyword
Fixes #129
> Fix so daysUntilClose keyword can be used under the pulls or issues keyword

- README.md
Actual link to the license return 404 as it's written licen**c**e.
> Fix license link in README.

- lib/stale.js
- package.json
- test/stale.test.js
Fixes #151 
Setting `"testEnvironment":"node"` broke this test:
https://github.com/probot/stale/blob/11629d71c98ee95e7da1a30085c15dcd684a189d/test/stale.test.js#L59
It seemed that the `await` was returning early, and after some tinkering I think I figured the issue:
https://github.com/probot/stale/blob/11629d71c98ee95e7da1a30085c15dcd684a189d/test/stale.test.js#L109
removing the `return` fixed the problem, though to be honest I am quite new to this world of promises and node and am not entirely sure why ¯\\_(ツ)_/¯
> Fix test suites and stale.js test

- README.md
- Made the comment for the key `daysUntilClose`, of the example config in the README.md file, more descriptive.
Fixes #153
> Fix daysUntilClose comment in example config file

- index.js
- lib/stale.js
- package.json
- test/schema.test.js
- test/stale.test.js
resolves #159
This PR updates standard to v12 (see the v12 changelog [here](https://standardjs.com/changelog.html#1200---2018-08-28)). 
After installing v2, I ran `npx standard --fix` to resolve violations that standard was newly reporting.
> chore(package): update standard to v12

- lib/schema.js
- test/schema.test.js
The default message posted by the bot is unnecessarily harsh and final-sounding, which has resulted in a lot of grief, summarized in #67.
Interestingly enough, even this repo decided against using the default message and has been using a friendlier and more constructive message for a while.
This change makes that message the default, so that other communities using this bot get a more positive experience out of the box.
> Make default comment friendlier and actionable (fixes #67)

- lib/schema.js
- package-lock.json
- package.json
I ran across this message at:
https://www.npmjs.com/package/joi
```
This package has been deprecated
Author message:
This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
```
> Use latest joi

- README.md
Rewording the description under _How are issues and pull requests considered stale?_ and cleaned up a wild double-space.
> README.md - Rewording and spacing corrections

- index.js
The `unmark` functionality is neither returning nor `await`-ing the `Promise` returned from the call to `Stale#unmarkIssue`.
This is not strictly necessary but would be the best practice to avoid hypothetical race conditions when invoking `unmark` but then continuing on before actually verifying the status/result of the inner activity.
If this is specifically  **not** desired, then I would instead suggest adding a comment here to explain why.
> Await the async result of unmarking an issue
