probot/stale

index.js
lib/paginate.js
lib/stale.js

Here's a vodoo method to handle pagination of GitHub requests.
If this actually works, it should be added in the github client or probot core.

Pagination

---

README.md
docs/deploy.md

Move deployment docs to centralized docs
cc https://github.com/probot/probot/pull/114

Move docs for deployment

---

lib/stale.js

Addresses #25
For now, this filters out locked issues and doesn't process them at all.
Tested on https://github.com/lee-dohm/bot-test/issues?q=is%3Aissue

Add filters for locked issues to prevent errors

---

README.md

Fixes #35
References #34 and #33

Add some troubleshooting documentation to the README file

---

.env.example
README.md
app.json
docs/deploy.md
package.json

Renames all instances of "GitHub Integration" to "GitHub App"

Integration => App

---

index.js
package-lock.json
package.json

https://github.com/probot/visitor/pull/7 renames the `probot-visitor` module to `probot-scheduler` and refactors it to trigger events instead of taking a callback.

Update from visitor to scheduler

---

index.js
package-lock.json
package.json

Use `context.config` added in https://github.com/probot/probot/issues/141

Use context.config to load config file

---

index.js
package-lock.json
package.json

Updates to latest version of probot.

Update probot 0.10.0

---

index.js
lib/defaults.js
lib/stale.js
package-lock.json
package.json

Since stale is the most popular probot app, I figured it should be the first to swap to standard lint!
Also, this was my first time bumbling around in stale so I wasn't sure the best way to test I didn't break anything 😬

Update probot and swap to standard lint

---

package.json
test/stale.test.js

cc https://github.com/probot/probot/issues/288

Migrate to jest

---

README.md

This has been raised enough times that I think it's worth documenting.
I wanted to hit on these points:
- there are finite resources
- a mountain of issues is paralyzing
- this makes the implicit explicit
- it only takes a comment to keep the conversation going
cc people who I know I've talked with this about: @JasonEtco @gr2m @lee-dohm @mikemcquaid

Attempt to articulate rationale for closing stale issues

---

CONTRIBUTING.md
README.md
package.json

docs: Minor changes following audit

---

index.js
package.json
test/stale.test.js

`^6.2.0` -> `7.0.1`
`robot` -> `app`
`createRobot` -> `Application`
`robot = createRobot()` -> `app = new Application()`

update probot to v7

---

README.md

Related to #155 @hiimbex - let me know if this fits the bill! 😊🤖️🕔

Add section to set up timing expectations ⌚️

---

package.json

fix(package): update probot to version 7.3.1

---

.gitignore
index.js
newrelic.js
package-lock.json
package.json

Getting us setup with some better monitoring since this is starting to get a lot of installations.

Setup newrelic

---

lib/stale.js

To Fix #207 
> I tried to introduce stale bot to comment stale issues which has specific label, but stale bot has marked all issues. 
I just fixed this! I hope this PR will be merged !! 😘

Bugfix onlyLabels

---

lib/stale.js
test/stale.test.js

Double-check issue state is not closed before acting

---

test/stale.test.js

Will conflict with similar tests added in #269, so should probably wait until after that one is merged.  🤷‍♂

Add tests to ensure locked issues are not acted on

---

README.md

The `How long will it take?` section tells to expect results within 24 hours. Use this time window in the Usage as well.
-----
[View rendered README.md](https://github.com/tyll/stale/blob/patch-1/README.md)

README: Adjust expectations for initial results
